name: GH Actions playground

on:
  deployment_status:
jobs:
  conditionally:
    if: |
      github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment_status.target_url, 'hogwarts') &&
      contains(github.event.deployment_status.environment, 'Production')
    name: Conditionally Print
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_DEPLOYMENT: ${{ toJson(github.event.deployment) }}
          GITHUB_DEPLOYMENT_STATUS: ${{ toJson(github.event.deployment_status) }}
        run: |
          echo "Was run because the condition was met.. now I'm going to emulate a really slow test"
          sleep 300
          echo "Done sleeping"
