name: GH Actions Required silly example

on:
  push:
jobs:
  required_check:
    name: Required print
    runs-on: ubuntu-latest
    steps:
      - name: Required check
        run: |
          echo "Required check"
